---

 - hosts: all
   become: yes

   tasks:

    - name: Install script
      template:
        src: /etc/ansible/shablon/test.sh
        dest: /home/ansible-admin/test.sh
        mode: 0777
    - name: Line test
      lineinfile:
       path: /home/ansible-admin/test.sh
       insertafter: EOF
       line: "{{ item }}"
       state: present
      with_items:
      - 'date &>> /var/log/web.log'
      - 'nginx -t &>>/var/log/web.log'
